name: Run Image Generator

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # specify your Node.js version

    - name: Install dependencies
      run: |
        npm install

    - name: Set Env vars
      run: |
        touch .env
        echo "TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" >> .env
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
        echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
        echo "AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}" >> .env

    - name: Run Image generator
      run: |
        npm run pullDb
        npm run increment
        npm run generate
        npm run upload
        npm run pushDb
